image: "archlinux:latest"

stages:
  - build
  - test

build:
  stage: build
  needs: []
  script:
    - pacman -Syu --noconfirm m4 make openssh subversion rsync arch-install-scripts git bzr mercurial diffutils asciidoc
    - make PREFIX=/usr
    - make PREFIX=/usr DESTDIR=build install

check:
  stage: test
  needs: []
  script:
    - pacman -Syu --noconfirm m4 make openssh subversion rsync arch-install-scripts git bzr mercurial diffutils asciidoc shellcheck
    - make check || true
    - SHELLCHECK_OPTS="-S error" make check
